import calendar
print(calendar.weekheader(3))
print()
print(calendar.firstweekday())
print()
print(calendar.month(2022, 3))
print(calendar.monthcalendar(2022, 3))
print(calendar.calendar(2022))
day_of_the_week = calendar.weekday(2022, 3, 23)
print(day_of_the_week)
is_leap = calendar.isleap(2022)
print(is_leap)